### ISSUE TITLE
resize in shiny?

### ISSUE THREAD

**Issue by MayaGans** [juba/robservable#36]
Hi! First of all this package is absolutely amazing thank you SO much I'm just starting to scratch the surface with it. This could be just my d3 code so please excuse me if so but when I render my chart cell in shiny it's not properly scaling to the dimensions of its container. 

```
library(shiny)
ui <- fluidPage(
    sidebarLayout(
        sidebarPanel(
            sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30)
        ),
        mainPanel(
           robservable::robservable(
               "@mayagans/timeseries",
               "chart"
           )
        )
    )
)
server <- function(input, output) {
}
shinyApp(ui = ui, server = server)

```

Any tips? Thanks!

**Comment by juba** [comment]
Hi,

First, thanks for your feedback, I'm really glad that `robservable` can be useful, and very curious what people may do with it !

Concerning your resizing problem. First, there's one thing you could do that may improve resizing a bit at least when your chart is displayed alone in RStudio viewer (ie outside of a Shiny app) : currently in your notebook your chart width is fixed at 900px in the `dimensions.width` property. If you replace the 900 value by Observable's special `width` value, resizing should be more "natural".

The second point is that, indeed, resizing doesn't work when your chart is included in Shiny (and the problem is not caused by your chart, I can reproduce it with others). I'll take a look into it and let you know when, hopefully, I'll find a solution.

Thanks !

**Comment by juba** [comment]
Oh, in fact it was much simpler than I thought, I think the problem comes from the fact that you inserted your chart directly in your `ui` when it must be rendered in your `server` part : 

```r
library(shiny)
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      sliderInput("bins",
                  "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)
    ),
    mainPanel(
      robservableOutput("chart")
    )
  )
)
server <- function(input, output) {
  output$chart <- renderRobservable(
    robservable::robservable(
    "@mayagans/timeseries",
    include = c("chart")
  )
  )
}
shinyApp(ui = ui, server = server)
```

But I think the chart looks better if you set `dimensions.width` as `width` instead of a fixed number.

**Comment by MayaGans** [comment]
Sick! Thank you SO much! [Up next: going to try to add an update function so the user can select different data via R and trigger a pretty transition...] Thank you again!!

**Comment by juba** [comment]
You're welcome !
For animated charts with transitions, you may take a look at this example :

https://observablehq.com/@juba/updatable-bar-chart

As you said you have to add an update method to your chart, and pass your data as an argument to this method, so that your chart cell doesn't directly depends on your data and is not entirely redrawn each time they change (maybe you are well aware of that, my apologies if this is the case).

Of course the pattern is not mine, I took it from Mike Bostock :-)

https://observablehq.com/@d3/sortable-bar-chart

**Comment by MayaGans** [comment]
Thank you SO much for your help!! Hopefully I'm not too annoying and can
ask you another question :) -- I want to make this notebook in shiny:
https://observablehq.com/@mayagans/cdisc-time-series-plot-with-update
but I want the viewof part to be a shiny input:

library(shiny)
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(

      #instead of the viewof

      selectInput("PARAMS", "NULL", c("GL", "SA")
    ),
    mainPanel(
      robservableOutput("chart")
    )
  )
)
server <- function(input, output) {
  output$chart <- renderRobservable(
    robservable::robservable(
    "@mayagans/cdisc-time-series-plot-with-update",
    include = c("chart")
  )
  )
}
shinyApp(ui = ui, server = server)


Does that make sense? Any help appreciated!
